### ISSUE TITLE
Generate text token and audio token at the same time is time costing, why not consider generate audio token only when it comes to speech2speech task?

### ISSUE THREAD

**Issue by lucasjinreal** [gpt-omni/mini-omni#10]
Hi, just wondering why must generate text token and audio token at the same time

**Comment by superFilicos** [comment]
Because audio tokens are designed primarily for audio reconstruction and don't simultaneously guarantee strong semantic information and high speech quality, we found that the model started producing gibberish during our experiments

**Comment by mini-omni** [comment]
hi, basiclly, we found that directly generating audio tokens was hard, and you may refer to: https://github.com/gpt-omni/mini-omni/issues/11#issuecomment-2329847459

**Comment by lucasjinreal** [comment]
Does generate text token && audio token at the same time would cost abot 2x time compare with generate text or audio token only?

**Comment by mini-omni** [comment]
> Does generate text token && audio token at the same time would cost abot 2x time compare with generate text or audio token only?

not really 2x times, the only different part is the final lm_head, and the text head is much larger, in our case, the text head is about 150000, the audio head is about 28000.

**Comment by lucasjinreal** [comment]
In terms of generate forward times, it should equal to the output text length, looks like 1.4x slower than pure text generation

**Comment by mini-omni** [comment]
> In terms of generate forward times, it should equal to the output text length, looks like 1.4x slower than pure text generation

could you please explain why it is 1.4x slower?
in my opinion, theoretically, In the original LLM, the computation of the lm_head part is 'a', and the rest is 'b'. The additional computation of the audio_head is approximately 0.19a, making the total computation around 1.19a + b.

**Comment by lucasjinreal** [comment]
Hello, if certain sounds cannot be strictly represented by words, how would that be synthesized? Also, if the words are a mixture of multiple languages, how will it behave?

**Comment by mini-omni** [comment]
> Hello, if certain sounds cannot be strictly represented by words, how would that be synthesized? Also, if the words are a mixture of multiple languages, how will it behave?

1. In my opinion, it's all about data. I think any sound can be reprented as text description, e.g. |braking| |raining|, and these special words can be used as the guidance or something like this. 
2. I think it's just like multi-lingual TTS, if training with multi-lingual data, it will just read it accordingly.

**Comment by lucasjinreal** [comment]
@mini-omni. Hello. Thank you for your answer. In your opinion, what might the GPT4O solution possibly be?

**Comment by mini-omni** [comment]
I hope I know the answer, but sadly no, I dont know. 

I will close it for now, please feel free to re-open.
