### ISSUE TITLE
Empty Audio for Gradio

### ISSUE THREAD

**Issue by MarcoFerreiraPerson** [gpt-omni/mini-omni#100]
Hello,

I am getting an error were when I run the gradio script audio does not return, however the server outputs text.

![image](https://github.com/user-attachments/assets/a7256087-d5cb-4dea-b10f-05704ae3e7c4)

![image](https://github.com/user-attachments/assets/69be3971-b12e-47f6-92dc-de526a33e2a9)

**Comment by mini-omni** [comment]
hi, could you please discribe your gradio version and testing environments?

**Comment by MarcoFerreiraPerson** [comment]
I updated the gradio version and it fixed it
