### ISSUE TITLE
VoiceAssistant-400K 数据集如何生成的

### ISSUE THREAD

**Issue by ltcxjtu** [gpt-omni/mini-omni#104]
关于这部分数据的构造问题；看论文我们我只能看到数据的文本部分如：Alpaca-GPT4，但仍然无法清晰的知道音频是怎么合成出来的。

**Comment by superFilicos** [comment]
输入部分使用cosytts，输出部分使用内部的模型哈。这个我们理解大家的需求不一样，所以没放出来输出的音频，不过我们都是合成的数据，用开源的语音合成模型我理解问题也不大。

**Comment by ltcxjtu** [comment]
我看你们输入语音的音色很丰富，而且连呼吸声，甚至小的冲击噪声也可以偶尔存在；如果要合成这么多种说话人的音色，你是加了引导音频吗？看它们官网的话：prompt_speech_16k = load_wav('zero_shot_prompt.wav', 16000)
for i, j in enumerate(cosyvoice.inference_zero_shot('收到好友从远方寄来的生日礼物，那份意外的惊喜与深深的祝福让我心中充满了甜蜜的快乐，笑容如花儿般绽放。', '希望你以后能够做的比我还好呦。', prompt_speech_16k, stream=False)):
    torchaudio.save('zero_shot_{}.wav'.format(i), j['tts_speech'], 22050)；用的是这种吗，加入了引导音频。。。我记得cosyvoice只有 英文男和英文女两种默认英文音色

**Comment by mini-omni** [comment]
@ltcxjtu hi, 我们就是使用的cosyvoice，生成不同的音色是通过不同audio prompt实现的。

**Comment by wwfcnu** [comment]
如果要生成多情感的语音，也可以通过cosyvoice生成吗

**Comment by mini-omni** [comment]
@wwfcnu 具体可以根据你的需求使用cosyvoice试试，多情感效果不太确定如何。

**Comment by tianzhangwu** [comment]
> 输入部分使用cosytts，输出部分使用内部的模型哈。这个我们理解大家的需求不一样，所以没放出来输出的音频，不过我们都是合成的数据，用开源的语音合成模型我理解问题也不大。

@mini-omni 您好，您在论文中提到，VoiceAssistant-400k是用GPT-4o 生成的，这里说的“输出部分使用内部的模型”怎么理解呢？

**Comment by mini-omni** [comment]
@tianzhangwu VoiceAssistant是通过gpt-4o对回复进行改写，使回复在内容相近的情况下，更符合口语对话的场景。输出部分用的内部模型是指，将回复内容转为语音是用的内部的TTS系统。
