### ISSUE TITLE
不支持移动端访问主机部署streamlit的服务嘛？

### ISSUE THREAD

**Issue by loredunk** [gpt-omni/mini-omni#106]
在主机上部署了这个streamlit服务之后，用移动端通过自签名的ssl访问https的服务，但是发现没法调用麦克风。是pyaudio的问题？还是streamlit的问题？

在本主机起服务，并且在主机上访问这个streamlit网页是work的，可以在web正常使用麦克风。

**Comment by mini-omni** [comment]
应该是移动端不支持pyaudio这套录音逻辑。
