### ISSUE TITLE
VoiceAssistant-400K

### ISSUE THREAD

**Issue by UestcJay** [gpt-omni/mini-omni#107]
Thanks for your great work! Any plan to open the data production process of VoiceAssistant-400K?

**Comment by mini-omni** [comment]
Hi, for the data processing, we use cosyvoice for TTS (input audio) and SNAC for output audio encoding, you may refer to these projects for more info.

**Comment by mini-omni** [comment]
we use open-source datasets, you may refer to tech report the dataset sources.
