### ISSUE TITLE
训练时audio feature和text token pad到的长度

### ISSUE THREAD

**Issue by vra** [gpt-omni/mini-omni#109]
HI @mini-omni ,想问下训练dataloader中，audio_feature pad到多长的时序维度呢，text token呢，现在设置audio_feature 时序pad到T=1500，max_seq_length设置为2048，训练异常的慢，核心原因是需要推理(max_seq_length-T+2)次才能拿到整体的logits来与gt toekn 算loss（[参考代码](https://github.com/gpt-omni/mini-omni/blob/main/litgpt/generate/base.py#L770))，想了解下你们在实验中设置的T和max_seq_length为多少

**Comment by mini-omni** [comment]
hi, 训练loss计算可以参考：https://github.com/Lightning-AI/litgpt/blob/main/litgpt/pretrain.py#L310
我们训练过程中max_seq_length为2048，所以seq都pad到这个长度方便并行运算，你也可以按照某个batch的最大长度来做patch，计算loss是并行的，不需要用generate的方式来迭代计算。

**Comment by vra** [comment]
@mini-omni 感谢解答， 还有一些疑问：pretrain.py里面的loss是针对预测下一个token的场景而设计的，那对应到asr中，就是根据第一个音素预测第二个音素，感觉不太符合任务的定义（输入所有audio预测对应的文本)
另外在litgpt发现有问答对的loss计算的方式（[代码](https://github.com/Lightning-AI/litgpt/blob/main/litgpt/finetune/adapter.py#L292)），感觉更合适这个任务？

**Comment by mini-omni** [comment]
@vra asr任务是输入audio，根据audio做预测对应的文本序列，audio部分不用计算loss，只保留audio部分的loss。你引用的代码就是计算loss用的方法。
