### ISSUE TITLE
【Training复现问题】三个stage具体训练周期数

### ISSUE THREAD

**Issue by vra** [gpt-omni/mini-omni#112]
Hi @mini-omni ,论文4.2部分提到了一些训练的参数设置，但没有提到训练的总epoch数，以及Stage1-3三个阶段的具体训练配置，因此提issue咨询一下：
1. 各个stage的训练周期数
2. 各个stage的lr设置

**Comment by mini-omni** [comment]
1. asr alignment训练10-20k steps, stage2 20-30k steps, stage3 50-60k steps，这个具体训练时长可能随数据会有差异，可做参考。
2. asr lr是4e-6, 1e-3; 其它阶段是 4e-6, 4e-4

**Comment by angus-deepmentor** [comment]
@mini-omni 
Dear authors, 


> 1. asr alignment训练10-20k steps, stage2 20-30k steps, stage3 50-60k steps，这个具体训练时长可能随数据会有差异，可做参考。
> 2. asr lr是4e-6, 1e-3; 其它阶段是 4e-6, 4e-4

In 2. you say other stages lr are 4e-4, but in the figure below it shows the final finetune stage lr is 5e-5.

<img width="1102" height="242" alt="Image" src="https://github.com/user-attachments/assets/efb81209-6b89-45fd-a9bc-a8d8fb62c59e" />

which of them is correct?
