### ISSUE TITLE
Broken demos?

### ISSUE THREAD

**Issue by nigelp** [gpt-omni/mini-omni#12]
I guess it would be so much more impressive if the demos weren't broken.

**Comment by superFilicos** [comment]
Hello, are you unable to view the demo video? It plays fine on my end.

**Comment by duaneking** [comment]
What is broken for you in the demo?

Are you on windows?

What errors are yo seeing?

**Comment by nigelp** [comment]
![omni2](https://github.com/user-attachments/assets/e29be0a0-183c-44df-8086-ae1a2d4ab6d1)

**Comment by mini-omni** [comment]
> ![omni2](https://private-user-images.githubusercontent.com/97901/364311807-e29be0a0-183c-44df-8086-ae1a2d4ab6d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Nzc3OTUsIm5iZiI6MTcyNTQ3NzQ5NSwicGF0aCI6Ii85NzkwMS8zNjQzMTE4MDctZTI5YmUwYTAtMTgzYy00NGRmLTgwODYtYWUxYTJkNGFiNmQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE5MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYjg1YWU1MzE1MDkwODA4OTFhN2Y0OWQwZTI2ZmRmZTQ0ZmI0ZmFkNTg5YmY3MmExMmUwMGE5NzZhMWFjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPq9rqyk1QEqH26ILpvcEZaz0S05mgvFKlVW3mQdtco)

hi, I think it may be the problem of internet or something related to your browser, try re-fresh the page? or you can clone the repo and the demo video is: data/demo_gradio.mov, you can play it with local video player.

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
