### ISSUE TITLE
How to get answer_audio of VoiceAssistant-400K dataset?

### ISSUE THREAD

**Issue by tianzhangwu** [gpt-omni/mini-omni#126]
Thank you for the excellent work by the team. While using the VoiceAssistant-400k dataset, I noticed that the answer section only contains the SNAC code and not the original audio. Could you please let me know how to obtain the original audio?

**Comment by tianzhangwu** [comment]
I got the solution.

**Comment by ZhengRachel** [comment]
> I got the solution.

@tianzhangwu Hi, could you please share how to get the answer audio?

**Comment by vra** [comment]
Here is the code snippet that I wrote to convert snac code to  wave audio:
```python
# coding: utf-8
from datasets import load_dataset
import soundfile as sf
import torch

from litgpt.utils.snac_utils import reconstruct_tensors
from litgpt.models.snac_model import SnacModel



ds = load_dataset("parquet", data_files="train-00000-of-00325.parquet")
train=ds['train']
d0 = train[100]
codes = d0["answer_snac"]
code_list = codes.split()
audio = reconstruct_tensors(code_list)

snac_model = SnacModel()
with torch.inference_mode():
    audio_hat = snac_model.decode(audio)

sf.write("answer.wav", audio_hat, samplerate=24000)
```

**Comment by ZhengRachel** [comment]
@vra Thank you for your help!! I used the wrong SNAC pretrained model and it is fixed now :).

**Comment by Ashbajawed** [comment]
> from litgpt.models.snac_model import SnacModel

hey there is no litgpt.models for me? 
 
I'm using below code but getting error

import torch
from snac import SNAC 
import soundfile as sf
from litgpt.utils.snac_utils import  reconscruct_snac, reconstruct_tensors
from datasets import load_dataset

dataset = load_dataset("gpt-omni/VoiceAssistant-400K")
snacmodel = SNAC.from_pretrained("hubertsiuzdak/snac_24khz").eval().to("cuda")
codes = sample["answer_snac"]
code_list = codes.split()
audio = reconstruct_tensors(code_list)
with torch.inference_mode():
    audio_hat = snacmodel.decode(audio)

Error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 15
     13 codes = sample["answer_snac"]
     14 code_list = codes.split()
---> 15 audio = reconstruct_tensors(code_list)
     16 with torch.inference_mode():
     17     audio_hat = snacmodel.decode(audio)

File ~/Researchwork/mini-omni/utils/snac_utils.py:113, in reconstruct_tensors(flattened_output, device)
    110         tensor3.append(flattened_output[i + 6])
    111         tensor3.append(flattened_output[i + 7])
    112         codes = [
--> 113             list_to_torch_tensor(tensor1).to(device),
    114             list_to_torch_tensor(tensor2).to(device),
    115             list_to_torch_tensor(tensor3).to(device),
    116         ]
    118 if n_tensors == 15:
    119     for i in range(0, len(flattened_output), 16):

File ~/Researchwork/mini-omni/utils/snac_utils.py:88, in reconstruct_tensors.<locals>.list_to_torch_tensor(tensor1)
     86 def list_to_torch_tensor(tensor1):
     87     # Convert the list to a torch tensor
---> 88     tensor = torch.tensor(tensor1)
     89     # Reshape the tensor to have size (1, n)
     90     tensor = tensor.unsqueeze(0)

ValueError: too many dimensions 'str'
