### ISSUE TITLE
Inquiry About the LLM Backbone of Mini-Omni

### ISSUE THREAD

**Issue by cwx-worst-one** [gpt-omni/mini-omni#127]
Hi, I would like to ask whether the LLM backbone of Mini-Omni is the same as that of Mini-Omni2, specifically Qwen2-0.5B Instruct, or if it is the Qwen2-0.5B (base model) instead.

Thank you for your help!

**Comment by vra** [comment]
Hi, @cwx-worst-one, As noted in the Mini-Omni and Mini-Omni2 paper, The backbone of Mini-Omni is Qwen2-0.5B, without insturct.

**Comment by cwx-worst-one** [comment]
Thank you, @vra, for your reply!
Oh, I just noticed that the latest version on arXiv has been updated to use the base version. Thanks again for the clarification! I'll go ahead and close this issue now.
