### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by BahamutRU** [gpt-omni/mini-omni#13]
Streamlit:

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=60808): Max retries exceeded with url: /chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E253D4460>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

Gradio:

Traceback (most recent call last):
  File "webui\omni_gradio.py", line 15, in <module>
    from inference import OmniInference
ModuleNotFoundError: No module named 'inference'

Doesn't work both.

**Comment by superFilicos** [comment]
emmm , it seems that your code doesn't run on our project as base folder

**Comment by BahamutRU** [comment]
i'm just idiot! =)
Please specify in the text that two applications need to be launched - a server (server.py) and a client (streamlit or gradio) separately and simultaneously. =)
