### ISSUE TITLE
输出不支持中文么？

### ISSUE THREAD

**Issue by kaixindelele** [gpt-omni/mini-omni#14]
我试了一些inference.py，将其中的测试文本替换成了中文，输出仍然是用英文回复。
由于我没有配置好音频的方案，所以还不知道音频的输入输出是否支持中文。

**Comment by Joseph513shen** [comment]
兄弟，显存占用大概多少？

**Comment by kaixindelele** [comment]
我4060 8G显存好像没爆显存，但不知道音频一起跑会不会爆

**Comment by Joseph513shen** [comment]
能跑是吧，按照作者的模型参数量，似乎显存占据只要4g以内就可以，我想用我的渣渣1070ti 8g试试看...

**Comment by duaneking** [comment]
恕我直言，您能让它正常工作吗？

在我按照“readme.md”文件说明操作后，它给出了很多错误。

**Comment by kaixindelele** [comment]
我暂时也不能，有一些基础的配置问题，也有一些奇奇怪怪的问题~

**Comment by duaneking** [comment]
谢谢。我遇到了同样的问题。我现在正在重新下载 lit_model.pth，看看是否有帮助。

**Comment by superFilicos** [comment]
大家好，抱歉给大家造成一些困扰。 以下是一些回复： 1. 模型暂不支持中文 2. 我们在linux服务器上完整运行readme没有遇到问题，您们可以发出来遇到的配置问题，我写一些通用的解决办法

**Comment by kaixindelele** [comment]
hh，没事儿，主要也是我本机没有一台Linux台式机，要么是win,要么是mac，要么是Linux远程。
所以会遇到各种问题。

**Comment by duaneking** [comment]
> 大家好，抱歉给大家造成一些困扰。 以下是一些回复： 1. 模型暂不支持中文 2. 我们在linux服务器上完整运行readme没有遇到问题，您们可以发出来遇到的配置问题，我写一些通用的解决办法

事实上，我说英语比说中文好得多，但我注意到这个帖子是用中文写的，所以我用中文来更好地“融入”。

我在 Windows 上运行这个，所以这可能是问题所在。

**Comment by superFilicos** [comment]
windows上应该是可以的，很多人给我发的邮件中运行正常hh, 如果遇到配置问题可以发一下截图

**Comment by superFilicos** [comment]
在windows上无法直接按照readme运行是我们的问题哈，实在抱歉会耽误大家时间解决他们 -.-

**Comment by superFilicos** [comment]
我这两天之内就用我的windows系统来"挑战一下"

**Comment by mini-omni** [comment]
> hh，没事儿，主要也是我本机没有一台Linux台式机，要么是win,要么是mac，要么是Linux远程。 所以会遇到各种问题。

目前我们只在linux环境下进行测试，但是linux远程启动服务，在本地使用mac是可以启动demo的，具体有什么问题可以分享一起看看哈。
如果是mac想在本地运行，可以参考：https://github.com/gpt-omni/mini-omni/issues/6

**Comment by netseye** [comment]
<img width="969" alt="image" src="https://github.com/user-attachments/assets/12390c9d-2097-45c9-a4d5-21bda74f578f">
intel的cpu的osx上无法安装torch2.3.1

**Comment by mini-omni** [comment]
@netseye requirments里的版本只是我们测试ok的版本，其它版本pytorch也可能支持运行，我目前还测试过2.2.0版本运行ok。

后续讨论与标题相关性较小，WinOS相关讨论可以新开issue，I'll close it for now, please feel free to re-open.
