### ISSUE TITLE
模型推理问题

### ISSUE THREAD

**Issue by william-ljz** [gpt-omni/mini-omni#16]
https://github.com/gpt-omni/mini-omni/blob/main/litgpt/model.py#189
感谢你们的好工作。但是我有一个疑问，看forward代码时，音频七层的推理的特征是在文本，一层一层推理出来的，和论文里面的延迟生成好像是不一致的，望解答。

**Comment by mini-omni** [comment]
hi, @william-ljz，谢谢关注，您的观察很仔细。目前开源的版本是不含tts adapter的版本，所以audio token与text token是同时生成的。延迟生成的本质是第一个step先生成text token, 然后下一个step再开始生成audio token。与是否包含tts adapter无关。

为了方便大家查阅，我让gpt翻译下问答，方便你也可以改成英文标题哈

translation
Q: When looking at the forward code, the features of the reasoning in the audio's seven layers are inferred step-by-step in the text, which seems inconsistent with the delayed generation described in the paper. Please clarify. 
A:  Your observation is very keen. The currently open-sourced version does not include the TTS adapter, so audio tokens and text tokens are generated simultaneously. The essence of delayed generation is that the first step generates text tokens, and the next step starts generating audio tokens. This is unrelated to whether the TTS adapter is included.

**Comment by GuangChen2016** [comment]
@mini-omni 你好，请问一下，第一个step生成的第一个text token后，然后下一个step开始生成基于第一个text token的audio token和text token，因为text token可能包含多帧的audio token，那么这一step生成的text token还是跟上一步一样吗？text token这样就会有很多repeat的现象？

**Comment by william-ljz** [comment]
@mini-omni 好的好的，我想问一下训练时候，您现在开源的代码看起来是基于离散token作为输入的，但是这里为什么要取平均呢，取平均是为了减少模型输入长度，但是感觉坏破坏信息完整性

**Comment by mini-omni** [comment]
> @mini-omni 你好，请问一下，第一个step生成的第一个text token后，然后下一个step开始生成基于第一个text token的audio token和text token，因为text token可能包含多帧的audio token，那么这一step生成的text token还是跟上一步一样吗？text token这样就会有很多repeat的现象？

不会有重复的现象，我们不做显性的text audio token对齐，具体的对齐是由模型自己去学的。生成过程中，text audio按照自己的逻辑去生成，生成完成后会直接在后面补充<text_pad>，直到audio token生成完毕。

**Comment by mini-omni** [comment]
> @mini-omni 好的好的，我想问一下训练时候，您现在开源的代码看起来是基于离散token作为输入的，但是这里为什么要取平均呢，取平均是为了减少模型输入长度，但是感觉坏破坏信息完整性

代码中输入是经过whipser编码后的连续特征，取平均是实现过程中为了方便复制了多份，通过取平均保证值不变，单纯为了是实现方便。不会涉及输入长度的变化。

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
