### ISSUE TITLE
what is the fastest ? A1A2, asr,  T1A2, T1T2, A1T2, A1A2-batch ?

### ISSUE THREAD

**Issue by zoldaten** [gpt-omni/mini-omni#19]
hi.

i am testing on my raspberry pi 4b on cpu.
what is the fastest one to use ?

https://youtu.be/UKHUE8WOQYU

**Comment by mini-omni** [comment]
If the compute is limited, then I suppose the T1T2 will be the fatest, cause the sequence is shorter, and A1A2-batch will be the slowest.
