### ISSUE TITLE
When to release VoiceAssistant-400K dataset

### ISSUE THREAD

**Issue by HQYSS** [gpt-omni/mini-omni#2]
请问下作者，论文中提到的VoiceAssistant-400K什么时候能发布出来呢，谢谢

**Comment by deyituo** [comment]
Waiting for your great training code!

**Comment by mini-omni** [comment]
For now, we are sorting things out. The dataset will come out shortly. Regarding the training code, there is currently no definitive release timeline.

**Comment by MonolithFoundation** [comment]
Is the dataset currently available?

**Comment by mini-omni** [comment]
the dataset is uploading, and the path will be: https://huggingface.co/datasets/gpt-omni/VoiceAssistant-400K (if the uploading process goes well)
