### ISSUE TITLE
how to use `curl` cli to get response

### ISSUE THREAD

**Issue by BrenchCC** [gpt-omni/mini-omni#21]
My Linux system can not open the website to use the server.

**Comment by mini-omni** [comment]
Hi, firstly, you should start the server, in local or remote. Then, you can run the streamlit demo or gradio demo locally and set the API_URL accordingly.
I don't think curl with work, cause the output of the server is audio streaming.
If there is any problem to start the demo, please give more detail, and i'm glad to help.

**Comment by BrenchCC** [comment]
> Hi, firstly, you should start the server, in local or remote. Then, you can run the streamlit demo or gradio demo locally and set the API_URL accordingly.
> 
> I don't think curl with work, cause the output of the server is audio stream.
> 
> If there is any problem to start the demo, please give more detail, and i'm glad to help.

I can start the server properly but I can't connect to the external url since I use the remote server which give the same external url as the network url.
Can it run with CPU for some test，depite the slow speed？

**Comment by mini-omni** [comment]
hi @BrenchCC , you may refer to: https://github.com/gpt-omni/mini-omni/issues/6#issuecomment-2330245257 for cpu inference.
For the remote server, you need to find out how the local machine can access the remote server.

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
