### ISSUE TITLE
How to retrieve text midway before it gets synthesized?

### ISSUE THREAD

**Issue by SoberSalman** [gpt-omni/mini-omni#22]
Hi, I am trying to utilize Mini-Omni in my project and i would like to retrieve the text given out the ASR and with that make the model generate a specific answer or question

**Comment by mini-omni** [comment]
hi, I dont know what you mean "text given out the ASR". But you can get the output text as: [code](https://github.com/gpt-omni/mini-omni/blob/f076c7207026c0be145605f926594d024801bd44/inference.py#L502C56-L502C67) during the generation process.

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
