### ISSUE TITLE
无法识别系统的麦克风

### ISSUE THREAD

**Issue by future911** [gpt-omni/mini-omni#24]
![chat_mini_demo](https://github.com/user-attachments/assets/f91f97fc-f617-432f-a56c-c773df0683cc)

使用gradio启动，打开测试页面，点击麦克风图标后，提示找不到麦克风，但使用上传音频文件的方式进行测试，一切正常，帮忙看看是什么问题，如何处理。
注：系统的麦克风和使用AirPods 进行语音交互一切正常。

**Comment by mini-omni** [comment]
这个看起来可能跟本地配置相关，可以参考下：https://github.com/gradio-app/gradio/issues/6446

**Comment by pxz2016** [comment]
使用 https

**Comment by YMMF007** [comment]
如果你使用的是edge浏览器打开窗口，可以参考https://blog.csdn.net/baidu_31788709/article/details/125652048，修改浏览器设置，把对应的网站加入。

**Comment by YMMF007** [comment]
如果你使用的是edge浏览器打开窗口，可以参考[https://blog.csdn.net/baidu_31788709/article/details/125652048]
修改浏览器设置，把对应的网站加入。

**Comment by YMMF007** [comment]
谷歌浏览器参考
https://www.jianshu.com/p/db50f4003ad1

**Comment by mini-omni** [comment]
I will close it for now, please feel free to re-open.
