### ISSUE TITLE
Question about SNAC

### ISSUE THREAD

**Issue by hjzzju** [gpt-omni/mini-omni#3]
I am excited about your great idea and released codes, but I have some questions. In codes, you use SNAC codec, but SNAC 24KHZ says "This model compresses 24 kHz audio into discrete codes at a 0.98 kbps bitrate. It uses 3 RVQ levels with token rates of 12, 23, and 47 Hz". Why you use 7 tokens and how you deal with different token rates?

**Comment by superFilicos** [comment]
Hi, Snac codes have 3 levels, and tokens number of each level is [1,2,4], so there are 7 tokens in total for each frame.
