### ISSUE TITLE
运行server.py启动后，网页打开失败

### ISSUE THREAD

**Issue by YMMF007** [gpt-omni/mini-omni#30]
我的操作系统是Linux
按照文档给的步骤装好环境后，能正常运行server.py，但是打开对应网页会404
![46ce1c3c962df31b588895e0b355c9c](https://github.com/user-attachments/assets/d5758827-e753-4c25-a4e0-9ebdfd788be4)
![image](https://github.com/user-attachments/assets/a987bc3e-e3c9-4d16-b438-da52ac7211ea)
请问我应该怎么解决

**Comment by BrenchCC** [comment]
应该需要启动
```
pip install PyAudio==0.2.14
API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py
```
它本身只是一个服务开启，没有对应的前端页面，streamlit就是基于模型服务构建一个可操作的接口

**Comment by YMMF007** [comment]
> 应该需要启动
> 
> ```
> pip install PyAudio==0.2.14
> API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py
> ```
> 
> 它本身只是一个服务开启，没有对应的前端页面，streamlit就是基于模型服务构建一个可操作的接口

哦哦哦，谢谢您，我刚刚用streamlit启动了~之前用streamlit，但是下不来pyaudio，刚刚找到了解决方法~
