### ISSUE TITLE
再window11 下 的 pycharm下配置好环境运行 python webui/omni_gradio.py 出现如下的错误     

### ISSUE THREAD

**Issue by anstonjie** [gpt-omni/mini-omni#32]
(base) (venv) PS D:\ai3\mini-omni> python webui/omni_gradio.py                 
SupervisionWarnings: BoundingBoxAnnotator is deprecated: `BoundingBoxAnnotator` is deprecated and has been renamed to `BoxAnnotator`. `BoundingBoxAnnotator` will be removed in supervision-0.26.0.
Traceback (most recent call last):
  File "D:\ai3\mini-omni\webui\omni_gradio.py", line 15, in <module>
    from inference import OmniInference
ImportError: cannot import name 'OmniInference' from 'inference' (D:\ai3\mini-omni\venv\lib\site-packages\inference\__init__.py)

**Comment by BrenchCC** [comment]
参考一下，windows环境需要控制包导入的问题 #25

**Comment by BrenchCC** [comment]
> (base) (venv) PS D:\ai3\mini-omni> python webui/omni_gradio.py SupervisionWarnings: BoundingBoxAnnotator is deprecated: `BoundingBoxAnnotator` is deprecated and has been renamed to `BoxAnnotator`. `BoundingBoxAnnotator` will be removed in supervision-0.26.0. Traceback (most recent call last): File "D:\ai3\mini-omni\webui\omni_gradio.py", line 15, in from inference import OmniInference ImportError: cannot import name 'OmniInference' from 'inference' (D:\ai3\mini-omni\venv\lib\site-packages\inference__init__.py)

```
**if API_URL is None:
    sys.path.extend(['C:\\pythoncode\\mini-omni_deploy\\mini-omni'])
    from inference import OmniInference
    omni_client = OmniInference('./checkpoint', 'cpu')
    omni_client.warm_up()**
```
填入API URL来避免这个问题，`API_URL = os.getenv("API_URL", "http://10.11.50.35:60808/chat")`

**Comment by anstonjie** [comment]
好了 谢谢大佬
分别根据你的方法 在win11中 下面的两种方式 全部运行成功
streamlit run webui/omni_streamlit.py

和 python webui/omni_gradio.py


希望这个项目能够把中文加入 可以用中文对答

**Comment by mini-omni** [comment]
由于我们目前没有收集中文数据，目前暂不支持中文，期待开源社区后续会有大佬支持。

I'll close it for now, please feel free to re-open.
