### ISSUE TITLE
Chat Mini-Omni Demo start 后提示没有输出设备

### ISSUE THREAD

**Issue by future911** [gpt-omni/mini-omni#37]
omni_streamlit 启动后，在 web 页面点击 start 后报错，错误如下

![image](https://github.com/user-attachments/assets/1a0ccc34-3091-4701-9e52-e827fcd742a4)
![image](https://github.com/user-attachments/assets/284a1b82-5d39-42e6-a011-c605e7692683)
![image](https://github.com/user-attachments/assets/137f0a91-3c2d-46ef-9364-7a3969881de1)

客户端访问使用的 MacBook ，音响和耳麦一切正常，请各位老师帮忙看看

**Comment by BrenchCC** [comment]
streamlit有点问题，你会发现你的浏览器没有显示你在使用麦克风，我用gradio是可以的
![Snipaste_2024-09-06_17-15-13](https://github.com/user-attachments/assets/9d4664c1-f7f1-48f3-ba02-cba4a003f171)

**Comment by future911** [comment]
@BrenchCC
我使用 gradio 其他都正常，但是提示找不到麦克风，语音交互只能通过录音文件来交换
![image](https://github.com/user-attachments/assets/9a868980-5573-427d-b638-b08277902018)

**Comment by mini-omni** [comment]
我也是mac环境，使用的chrome浏览器，如果是streamlit，确认下本地有安装pyaudio，ffmpeg么？

**Comment by future911** [comment]
> 我也是mac环境，使用的chrome浏览器，如果是streamlit，确认下本地有安装pyaudio，ffmpeg么？

你好，这两个包均已安装
![image](https://github.com/user-attachments/assets/181154ae-44e2-4193-a83d-e06308715acc)

**Comment by pxz2016** [comment]
使用 https 协议才能启用麦克风

**Comment by pxz2016** [comment]
@mini-omni 
streamlit的demo需要在本地运行是吗？不能在云端linux服务器上运行吗？
pyaudio是一个Python库，它的主要设计目的是在本地运行时访问音频硬件

**Comment by mini-omni** [comment]
> @mini-omni streamlit的demo需要在本地运行是吗？不能在云端linux服务器上运行吗？ pyaudio是一个Python库，它的主要设计目的是在本地运行时访问音频硬件

@VJJJJJJ1 @pxz2016 hi，目前streamlit是依赖pyaduio，这是需要在本地运行的，无法支持云端运行本地访问。目前，我也不清楚如何用streamlit实现云端执行，本地访问，支持支持audio streaming，如果有方案欢迎分享。参考：https://github.com/whitphx/streamlit-webrtc-example/tree/main

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.

**Comment by Change0028** [comment]
> > @mini-omni streamlit的demo需要在本地运行是吗？不能在云端linux服务器上运行吗？ pyaudio是一个Python库，它的主要设计目的是在本地运行时访问音频硬件
> 
> @VJJJJJJ1 @pxz2016 hi，目前streamlit是依赖pyaduio，这是需要在本地运行的，无法支持云端运行本地访问。目前，我也不清楚如何用streamlit实现云端执行，本地访问，支持支持audio streaming，如果有方案欢迎分享。参考：https://github.com/whitphx/streamlit-webrtc-example/tree/main

或许可以尝试streamlit-webrtc，好像可以云端调用本地mic

**Comment by mini-omni** [comment]
@Change0028 streamlit-webrtc我有尝试，但调试没有完全成功。感兴趣，你也可以参考gradio-webrtc, https://github.com/gpt-omni/mini-omni2/pull/27
