### ISSUE TITLE
如果我直接想让他把我读出的中文语音直接翻译成英文读出来 应该调整那个参数或者方法 就是同声传译 应该怎么设置一下？

### ISSUE THREAD

**Issue by anstonjie** [gpt-omni/mini-omni#38]
我运行后发现我读中文他可以理解 并调用大模型 直接把英文的答案 读出来

如果我想让他直接把我读的中文  直接用英文读出来 应该怎么设置

就是里面提到的同声传译 应该修改那些参数

**Comment by mini-omni** [comment]
hi, 我们的训练数据中没有翻译相关的数据，也没有测试是否能支持同声传译，可以试试“please translate: 我是谁”。不过，不保证成功。理论上加一些翻译类的数据可以有效实现此类功能。

**Comment by anstonjie** [comment]
好的，我试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月07日 18:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [gpt-omni/mini-omni] 如果我直接想让他把我读出的中文语音直接翻译成英文读出来 应该调整那个参数或者方法 就是同声传译 应该怎么设置一下？ (Issue #38) |

hi, 我们的训练数据中没有翻译相关的数据，也没有测试是否能支持同声传译，可以试试“please translate: 我是谁”。不过，不保证成功。理论上加一些翻译类的数据可以有效实现此类功能。

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
