### ISSUE TITLE
About text instructed audio generation

### ISSUE THREAD

**Issue by MonolithFoundation** [gpt-omni/mini-omni#39]
Hi, text instructed is better to training, still have some further question in this manner: for those voices can not represent by words, how does it sysnthsis? For instance, GPT4o can simulate rain sound, animal sound, laugh, cry etc.

**Comment by mini-omni** [comment]
Hi, I think these can be represented as something like <rain> <bark> <laugh>, it is all about data.

**Comment by mini-omni** [comment]
I will close it for now, please feel free to re-open.
