### ISSUE TITLE
能否解释一下Batch Parallel Decoding？

### ISSUE THREAD

**Issue by NiHaoUCAS** [gpt-omni/mini-omni#4]
看了很多遍，还是没能理解。

我的理解是：
1. 有两个不同的样本
2. 经过一系列的操作后，达成的效果是：使用样本1作为输出，样本2的文本和音频作为输出。

麻烦帮忙看看是否有误。

另外：是否有开源训练代码的计划？

**Comment by superFilicos** [comment]
你好，batchdecode你可以这样理解。 同样一个音频输入，可以让模型进行音频输入-文本回答的任务，也可以让模型进行音频输入-音频回答的任务。batch就是让模型推理时用这两个任务组成一个batch，然后在transformer推理的过程中，音频回答那个任务会生成一个文本token和7个音频token对吧？ 把他的那个文本token丢掉，把文本回答那个任务生成的那个token放到那个位置去。这样语音的输出会是文本回答任务的文字。paper里写了在推理时文本是什么音频念的就是什么。同学可能有一个没搞清楚，模型进行音频输入-音频回答任务的时候生成的音频和文本不是两个答案，是一个答案的文字版和语音版。 Plus：技术员是新生在开学... 国内学校开学你懂滴，每天塞满讲座还不让请假..
谢谢。

**Comment by superFilicos** [comment]
可以加我微信呀 13810830993

**Comment by NiHaoUCAS** [comment]
谢谢你的回复，搞明白了。

**Comment by icemoon-creative** [comment]
如何控制模型是进行“音频输入-文本回答”还是“音频输入-音频回答”呢

**Comment by mini-omni** [comment]
> 如何控制模型是进行“音频输入-文本回答”还是“音频输入-音频回答”呢

inference过程中，根据任务special token，比如_answer_t, _answer_a 来进行控制。

**Comment by ranck626** [comment]
感谢！我也明白了
