### ISSUE TITLE
Start server but got 404 error

### ISSUE THREAD

**Issue by irrikrlla** [gpt-omni/mini-omni#40]
![image](https://github.com/user-attachments/assets/f590f708-816e-42c0-8832-8a033e380514)
After model-loading, I got a 404 error. What happened?

**Comment by mini-omni** [comment]
hi, which demo you run? streamlit or gradio? I think the problem maybe you use GET method, and server starts with POST method. Use example: https://github.com/gpt-omni/mini-omni/blob/main/webui/omni_streamlit.py#L127

**Comment by pli2014** [comment]
OmniChatServer code in the server.py, which use a post method for /chat api
