### ISSUE TITLE
用MAC电脑，即使用上MPS GPU了，运行webui/omni_streamlit.py，那是一个卡啊

### ISSUE THREAD

**Issue by Aaron-genai-superdev** [gpt-omni/mini-omni#41]
大家跟我一样吗？基本上AI说话的声音都是短短续续的。
如果是调整为纯CPU，更卡了。
看来这个模型是没法在普通电脑上运行了吗？

**Comment by mini-omni** [comment]
我的测试环境是linux 3090，整体速度是比较流畅的，cpu目前测试是会比较卡，mac没有实际测试过。模型整体差不多0.6B，整体计算量不算大的。

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
