### ISSUE TITLE
whisper.load_audio requires ffmpeg to work on your computer

### ISSUE THREAD

**Issue by DanWork123** [gpt-omni/mini-omni#42]
I noticed that running `python3 server.py --ip '0.0.0.0' --port 60808` will fail if ffmpeg is not installed on the computer. 
I guess the cause lies in whisper.load_audio. 
I was able to fix it by installing ffmpeg locally.

**Comment by mini-omni** [comment]
Thanks for pointing it out, I'll add it to README.
