### ISSUE TITLE
运行omni_streamlit.py的错误

### ISSUE THREAD

**Issue by taozhiyuai** [gpt-omni/mini-omni#51]
`
(omni) taozhiyu@Mac mini-omni % API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.31.86:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog
            
2024-09-08 09:23:05.625 Uncaught app exception
Traceback (most recent call last):
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "/Users/taozhiyu/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/taozhiyu/Downloads/mini-omni/webui/omni_streamlit.py", line 18, in <module>
    from utils.vad import get_speech_timestamps, collect_chunks, VadOptions
ModuleNotFoundError: No module named 'utils.vad'

`

`

import streamlit as st
import wave

# from ASR import recognize
import requests
import pyaudio
import numpy as np
import base64
import io
import os
import time
import tempfile
import librosa
import traceback
from pydub import AudioSegment
from utils.vad import get_speech_timestamps, collect_chunks, VadOptions

API_URL = os.getenv("API_URL", "http://127.0.0.1:60808/chat")

# recording parameters
IN_FORMAT = pyaudio.paInt16
IN_CHANNELS = 1
IN_RATE = 24000
IN_CHUNK = 1024
IN_SAMPLE_WIDTH = 2
VAD_STRIDE = 0.5

# playing parameters
OUT_FORMAT = pyaudio.paInt16
OUT_CHANNELS = 1
OUT_RATE = 24000
OUT_SAMPLE_WIDTH = 2
OUT_CHUNK = 5760

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

def run_vad(ori_audio, sr):
    _st = time.time()
    try:
        audio = np.frombuffer(ori_audio, dtype=np.int16)
        audio = audio.astype(np.float32) / 32768.0
        sampling_rate = 16000
        if sr != sampling_rate:
            audio = librosa.resample(audio, orig_sr=sr, target_sr=sampling_rate)

        vad_parameters = {}
        vad_parameters = VadOptions(**vad_parameters)
        speech_chunks = get_speech_timestamps(audio, vad_parameters)
        audio = collect_chunks(audio, speech_chunks)
        duration_after_vad = audio.shape[0] / sampling_rate

        if sr != sampling_rate:
            # resample to original sampling rate
            vad_audio = librosa.resample(audio, orig_sr=sampling_rate, target_sr=sr)
        else:
            vad_audio = audio
        vad_audio = np.round(vad_audio * 32768.0).astype(np.int16)
        vad_audio_bytes = vad_audio.tobytes()

        return duration_after_vad, vad_audio_bytes, round(time.time() - _st, 4)
    except Exception as e:
        msg = f"[asr vad error] audio_len: {len(ori_audio)/(sr*2):.3f} s, trace: {traceback.format_exc()}"
        print(msg)
        return -1, ori_audio, round(time.time() - _st, 4)

def warm_up():
    frames = b"\x00\x00" * 1024 * 2  # 1024 frames of 2 bytes each
    dur, frames, tcost = run_vad(frames, 16000)
    print(f"warm up done, time_cost: {tcost:.3f} s")

def save_tmp_audio(audio_bytes):
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmpfile:
        file_name = tmpfile.name
        audio = AudioSegment(
            data=audio_bytes,
            sample_width=OUT_SAMPLE_WIDTH,
            frame_rate=OUT_RATE,
            channels=OUT_CHANNELS,
        )
        audio.export(file_name, format="wav")
        return file_name

def speaking(status):

    # Initialize PyAudio
    p = pyaudio.PyAudio()

    # Open PyAudio stream
    stream = p.open(
        format=OUT_FORMAT, channels=OUT_CHANNELS, rate=OUT_RATE, output=True
    )

    audio_buffer = io.BytesIO()
    wf = wave.open(audio_buffer, "wb")
    wf.setnchannels(IN_CHANNELS)
    wf.setsampwidth(IN_SAMPLE_WIDTH)
    wf.setframerate(IN_RATE)
    total_frames = b"".join(st.session_state.frames)
    dur = len(total_frames) / (IN_RATE * IN_CHANNELS * IN_SAMPLE_WIDTH)
    status.warning(f"Speaking... recorded audio duration: {dur:.3f} s")
    wf.writeframes(total_frames)

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmpfile:
        with open(tmpfile.name, "wb") as f:
            f.write(audio_buffer.getvalue())
        file_name = tmpfile.name
        with st.chat_message("user"):
            st.audio(file_name, format="audio/wav", loop=False, autoplay=False)
        st.session_state.messages.append(
            {"role": "assistant", "content": file_name, "type": "audio"}
        )

    st.session_state.frames = []

    audio_bytes = audio_buffer.getvalue()
    base64_encoded = str(base64.b64encode(audio_bytes), encoding="utf-8")
    files = {"audio": base64_encoded}
    output_audio_bytes = b""
    with requests.post(API_URL, json=files, stream=True) as response:
        try:
            for chunk in response.iter_content(chunk_size=OUT_CHUNK):
                if chunk:
                    # Convert chunk to numpy array
                    output_audio_bytes += chunk
                    audio_data = np.frombuffer(chunk, dtype=np.int8)
                    # Play audio
                    stream.write(audio_data)
        except Exception as e:
            st.error(f"Error during audio streaming: {e}")

    out_file = save_tmp_audio(output_audio_bytes)
    with st.chat_message("assistant"):
        st.audio(out_file, format="audio/wav", loop=False, autoplay=False)
    st.session_state.messages.append(
        {"role": "assistant", "content": out_file, "type": "audio"}
    )

    wf.close()
    # Close PyAudio stream and terminate PyAudio
    stream.stop_stream()
    stream.close()
    p.terminate()
    st.session_state.speaking = False
    st.session_state.recording = True

def recording(status):
    audio = pyaudio.PyAudio()

    stream = audio.open(
        format=IN_FORMAT,
        channels=IN_CHANNELS,
        rate=IN_RATE,
        input=True,
        frames_per_buffer=IN_CHUNK,
    )

    temp_audio = b""
    vad_audio = b""

    start_talking = False
    last_temp_audio = None
    st.session_state.frames = []

    while st.session_state.recording:
        status.success("Listening...")
        audio_bytes = stream.read(IN_CHUNK)
        temp_audio += audio_bytes

        if len(temp_audio) > IN_SAMPLE_WIDTH * IN_RATE * IN_CHANNELS * VAD_STRIDE:
            dur_vad, vad_audio_bytes, time_vad = run_vad(temp_audio, IN_RATE)

            print(f"duration_after_vad: {dur_vad:.3f} s, time_vad: {time_vad:.3f} s")

            if dur_vad > 0.2 and not start_talking:
                if last_temp_audio is not None:
                    st.session_state.frames.append(last_temp_audio)
                start_talking = True
            if start_talking:
                st.session_state.frames.append(temp_audio)
            if dur_vad < 0.1 and start_talking:
                st.session_state.recording = False
                print(f"speech end detected. excit")
            last_temp_audio = temp_audio
            temp_audio = b""

    stream.stop_stream()
    stream.close()

    audio.terminate()

def main():

    st.title("Chat Mini-Omni Demo")
    status = st.empty()

    if "warm_up" not in st.session_state:
        warm_up()
        st.session_state.warm_up = True
    if "start" not in st.session_state:
        st.session_state.start = False
    if "recording" not in st.session_state:
        st.session_state.recording = False
    if "speaking" not in st.session_state:
        st.session_state.speaking = False
    if "frames" not in st.session_state:
        st.session_state.frames = []

    if not st.session_state.start:
        status.warning("Click Start to chat")

    start_col, stop_col, _ = st.columns([0.2, 0.2, 0.6])
    start_button = start_col.button("Start", key="start_button")
    # stop_button = stop_col.button("Stop", key="stop_button")
    if start_button:
        time.sleep(1)
        st.session_state.recording = True
        st.session_state.start = True

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            if message["type"] == "msg":
                st.markdown(message["content"])
            elif message["type"] == "img":
                st.image(message["content"], width=300)
            elif message["type"] == "audio":
                st.audio(
                    message["content"], format="audio/wav", loop=False, autoplay=False
                )

    while st.session_state.start:
        if st.session_state.recording:
            recording(status)

        if not st.session_state.recording and st.session_state.start:
            st.session_state.speaking = True
            speaking(status)

        # if stop_button:
        #     status.warning("Stopped, click Start to chat")
        #     st.session_state.start = False
        #     st.session_state.recording = False
        #     st.session_state.frames = []
        #     break

if __name__ == "__main__":
    main()
`

**Comment by taozhiyuai** [comment]
@BrenchCC 看看我发的issue,几个问题都没法解决

**Comment by mini-omni** [comment]
看起来已经解决了？我先close了, feel free to re-open.

**Comment by taozhiyuai** [comment]
> 看起来已经解决了？我先close了, feel free to re-open.

没有哦.问题多.你看我发的帖子

**Comment by mini-omni** [comment]
你这个帖子对应的问题是：ModuleNotFoundError: No module named 'utils.vad'
你需要在运行streamlit前先执行：export PYTHONPATH=./

**Comment by xinyinan9527** [comment]
> > 看起来已经解决了？我先close了, feel free to re-open.
> 
> 没有哦.问题多.你看我发的帖子

ModuleNotFoundError: No module named 'utils.vad'
这个问题，你可以把untils/assest下的文件复制到webui/assest/下面

**Comment by ffhelly** [comment]
> 你这个帖子对应的问题是：ModuleNotFoundError: No module named 'utils.vad' 你需要在运行streamlit前先执行：export PYTHONPATH=./

我也是这个问题。  装了 utils  也是这个提示没有vad。  
我也在使用前 执行了 export PYTHONPATH=./   也是如此。

**Comment by ffhelly** [comment]
> 你这个帖子对应的问题是：ModuleNotFoundError: No module named 'utils.vad' 你需要在运行streamlit前先执行：export PYTHONPATH=./

(omni) root@8ka:/kiwi/helly/music/mini-omni#  export PYTHONPATH=./
(omni) root@8ka:/kiwi/helly/music/mini-omni# API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.11.225:8501

2024-10-17 15:55:47.780 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/kiwi/helly/music/mini-omni/webui/omni_streamlit.py", line 17, in <module>
    from utils.vad import get_speech_timestamps, collect_chunks, VadOptions
ModuleNotFoundError: No module named 'utils.vad'


import sys
from pydub import AudioSegment
from utils.vad import get_speech_timestamps, collect_chunks, VadOptions

sys.path.extend(['/root/miniconda3/envs/omni'])

已经加入了sys   指向的是我的conda下 omni的路劲。

还是提示vad的错误

**Comment by ffhelly** [comment]
> > 你这个帖子对应的问题是：ModuleNotFoundError: No module named 'utils.vad' 你需要在运行streamlit前先执行：export PYTHONPATH=./
> 
> (omni) root@8ka:/kiwi/helly/music/mini-omni# export PYTHONPATH=./ (omni) root@8ka:/kiwi/helly/music/mini-omni# API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py
> 
> You can now view your Streamlit app in your browser.
> 
> Local URL: http://localhost:8501 Network URL: http://192.168.11.225:8501
> 
> 2024-10-17 15:55:47.780 Uncaught app exception Traceback (most recent call last): File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling result = func() File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec exec(code, module.**dict**) File "/kiwi/helly/music/mini-omni/webui/omni_streamlit.py", line 17, in from utils.vad import get_speech_timestamps, collect_chunks, VadOptions ModuleNotFoundError: No module named 'utils.vad'
> 
> import sys from pydub import AudioSegment from utils.vad import get_speech_timestamps, collect_chunks, VadOptions
> 
> sys.path.extend(['/root/miniconda3/envs/omni'])
> 
> 已经加入了sys 指向的是我的conda下 omni的路劲。
> 
> 还是提示vad的错误




我选择使用omni_gradio方式的时候，检测不到麦克风。
我用上传音频的方式 进行传输， 可以看到控制台有返回，但是在页面上 无法试听到具体的内容。

然后显示这样的内容：


/tmp/tmp5iipk7mh.wav: Invalid data found when processing input
  0%|▎                                                                             | 8/1931 [00:00<00:56, 34.06it/s]127.0.0.1 - - [17/Oct/2024 16:09:15] "POST /chat HTTP/1.1" 200 -
  2%|█▎                                                                           | 32/1931 [00:01<00:59, 31.94it/s]
text output: Hello! How can I assist you today?
127.0.0.1 - - [17/Oct/2024 16:10:08] "POST /chat HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/whisper/audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "/root/miniconda3/envs/omni/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', '/tmp/tmpimvh_ej8.wav', '-f', 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/flask/helpers.py", line 113, in generator
    yield from gen
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/kiwi/helly/music/mini-omni/inference.py", line 405, in run_AT_batch_stream
    mel, leng = load_audio(audio_path)
  File "/kiwi/helly/music/mini-omni/inference.py", line 140, in load_audio
    audio = whisper.load_audio(path)
  File "/root/miniconda3/envs/omni/lib/python3.10/site-packages/whisper/audio.py", line 60, in load_audio
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
/tmp/tmpimvh_ej8.wav: Invalid data found when processing input
  0%|▎                                                                             | 8/1918 [00:00<00:53, 35.52it/s]127.0.0.1 - - [17/Oct/2024 16:10:44] "POST /chat HTTP/1.1" 200 -
  5%|████                                                                        | 102/1918 [00:03<00:54, 33.34it/s]
text output: I'm sorry, but I don't have access to real-time weather data. However, I can provide you with a general overview of the weather forecast for today.

**Comment by mini-omni** [comment]
@ffhelly 可以试试最新的方案，加强了import的兼容性。可以确认下gradio的版本是否符合要求。
