### ISSUE TITLE
Problem with version torch 2.3.1

### ISSUE THREAD

**Issue by MatienkoAndrew** [gpt-omni/mini-omni#55]
macos (M1): sonoma 14.0
(omni) andrejmatienko@MacBook-Pro-Andrej-5 mini-omni % pip install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement torch==2.3.1 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.3.1

**Comment by mini-omni** [comment]
hi, I aslo test it will work with 
```
torch==2.2.0
torchvision==0.17.0
torchaudio==2.2.0
```
you can test with these versions.
