### ISSUE TITLE
文本转语音是不是无法支持中文？输入中文文本能否输出中文语音？

### ISSUE THREAD

**Issue by telepathHJY** [gpt-omni/mini-omni#57]

**Comment by superFilicos** [comment]
是的，我们的数据集中没有中文

**Comment by 808cn** [comment]
是的， 我也看了 tokenizer.json 文件的内容，好几种语言都有，恰好没有中文。
评论区也是中文最多，希望后面能支持中文。
当然支持中文语音输出工作量和难度要大很多，要从头训练和搞。

**Comment by mini-omni** [comment]
目前版本可能听懂一些中文，但输出只能是英文。中文文本理论上可以输入，但具体效果无法保证。
