### ISSUE TITLE
Is there any possibility for RAG with Mini-Omni?

### ISSUE THREAD

**Issue by yash-chudasama** [gpt-omni/mini-omni#59]

**Comment by superFilicos** [comment]
We believe the simplest approach is for a small model to determine, based on the semantics of the input, whether RAG is needed, and then append the relevant text to the input as supporting material.

**Comment by zzhiyun** [comment]
So when using RAG, do we search directly by voice or convert the voice into text for search? Is the knowledge base stored in voice information or text information?

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
