### ISSUE TITLE
The audio is shorter than the generated text and doesn't say the whole thing.

### ISSUE THREAD

**Issue by Enchante503** [gpt-omni/mini-omni#60]
The audio is shorter than the generated text and doesn't say the whole thing.

mini-omni is great,
is it possible to improve fluency and adjust speaking speed?
Is it possible to display the generated text on the demo screen along with the audio?

**Comment by superFilicos** [comment]
Yes, because the audio data used for training is typically shorter, while the text output tends to be longer, it can easily result in incomplete speech when the text is particularly long.

**Comment by mini-omni** [comment]
> The audio is shorter than the generated text and doesn't say the whole thing.
> 
> mini-omni is great, is it possible to improve fluency and adjust speaking speed? Is it possible to display the generated text on the demo screen along with the audio?

1. For the released model,  it is not. But it is possible to improve fluency and adjust speaking speed with more natural dialogue data.
2. It is possible, we print the output text in server log. But we dont have time to do that for now.
