### ISSUE TITLE
运行server.py，进度条只加载到4%，这正常吗

### ISSUE THREAD

**Issue by YMMF007** [gpt-omni/mini-omni#62]
![image](https://github.com/user-attachments/assets/f4680289-07a2-4b94-bec1-c22e586540d2)

**Comment by Evgeny105** [comment]
I added to inference.py:
torch.set_float32_matmul_precision("high")

**Comment by YMMF007** [comment]
Thanks！

**Comment by superFilicos** [comment]
正常的，进度条的总长度是推理的最长，默认2048，不过扩展到最大也无所谓，进度条结束的长度就是实际有多少组token就说完啦

**Comment by YMMF007** [comment]
噢噢噢噢，谢谢~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月10日(星期二) 下午2:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gpt-omni/mini-omni] 运行server.py，进度条只加载到4%，这正常吗 (Issue #62)














 
正常的，进度条的总长度是推理的最长，默认2048，不过扩展到最大也无所谓，进度条结束的长度就是实际有多少组token就说完啦
