### ISSUE TITLE
Can we change base model? for LLM and TTS in batch processing?

### ISSUE THREAD

**Issue by ankit-chotaliya** [gpt-omni/mini-omni#63]

**Comment by mini-omni** [comment]
Hi, if you want to change the base model, you need to re-train the audio part.

**Comment by SJenishaJ** [comment]
yes i ready to retrain can i get the training script and overall documentation and dataset this is my email sbharathi16042001@gmail.com

**Comment by mzeidhassan** [comment]
hi @mini-omni can you please share documentation on how to retrain the audio part? Can I also train it on different language other than English?

**Comment by mini-omni** [comment]
> hi @mini-omni can you please share documentation on how to retrain the audio part? Can I also train it on different language other than English?

hi, for the training process, you may refer to the tech report in the README, thx.

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
