### ISSUE TITLE
推理报错：CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by yz53665** [gpt-omni/mini-omni#65]
![20240911-175445](https://github.com/user-attachments/assets/68ebb351-6682-4777-b4d1-fc92d1370e8b)

python: 3.10.14
cuda: 12.2（11.6也试过，一样的问题）
GPU：A800-SXM4-80GB

其它python第三方库参考教程使用pip install -r requirement.txt安装

**Comment by mini-omni** [comment]
我使用的cuda版本是12.2，测试显卡是3090
可以参考下[这个](https://stackoverflow.com/questions/68106457/pytorch-cuda-error-an-illegal-memory-access-was-encountered)呢？是因为OOM么？

**Comment by mini-omni** [comment]
I will close it for now, please feel free to re-open.
