### ISSUE TITLE
Architecture difference from technical report?

### ISSUE THREAD

**Issue by seaplus296** [gpt-omni/mini-omni#67]
in technical report, architecture of TTS Adapter is additional 6 transformer blocks, 
<img width="921" alt="image" src="https://github.com/user-attachments/assets/33a80f5b-a4de-4356-8ed4-61a0f230b516">

but in config in [link](https://huggingface.co/gpt-omni/mini-omni/blob/main/model_config.yaml), can not see such architecture. maybe post_adapter?

but no post_adapter in config and checkpoint.

**Comment by mini-omni** [comment]
Hi, @seaplus296 you are right, post_adapter is the tts_adapter. But the open source version do not include tts_adapter.

**Comment by seaplus296** [comment]
@mini-omni Then, is paper version has 30-layer transformer for tts-output? which means do not sharing lm head between code vocab and lm vocab?

**Comment by seaplus296** [comment]
By the way, I think it would be good to notify that model here is not reported in technical report if it's different....

**Comment by mini-omni** [comment]
> @mini-omni Then, is paper version has 30-layer transformer for tts-output? which means do not sharing lm head between code vocab and lm vocab?

yes, we add extra 6-layer for tts-adapter, and they do not share lm_head (even for the version with tts-adapter)

**Comment by mini-omni** [comment]
> By the way, I think it would be good to notify that model here is not reported in technical report if it's different....

thanks for your suggestion, I'll add it in the README.

**Comment by seaplus296** [comment]
@seaplus296 Thanks. Finally is there any performance difference between report's architecture and open-source version? Why architecture changed?

**Comment by mini-omni** [comment]
> @mini-omni Thanks. Finally is there any performance difference between report's architecture and open-source version? Why architecture changed?

The open-source version is the one used for synchronous development and experimental comparison. In our subjective evaluation, the version with the TTS-adapter has less impact on text processing capabilities.

**Comment by seaplus296** [comment]
@mini-omni Thank you for kind replies.

**Comment by seaplus296** [comment]
@mini-omni sorry, i have some follow-up question. If open-source version's tts adapter is just vocab expansion how it is trained in stage 1? only expanded parameters?

**Comment by mini-omni** [comment]
the open-source version does not include tts-adapter, and the tts-adapter is mainly adding more layers.
