### ISSUE TITLE
streamlit error when click "start" button. 

### ISSUE THREAD

**Issue by Emotibot5** [gpt-omni/mini-omni#68]
see the error info:

84|omni_we |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
84|omni_we |     result = func()
84|omni_we |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
84|omni_we |     exec(code, module.__dict__)
84|omni_we |   File "/data/app/ai/mini-omni/webui/omni_streamlit.py", line 257, in <module>
84|omni_we |     main()
84|omni_we |   File "/data/app/ai/mini-omni/webui/omni_streamlit.py", line 242, in main
84|omni_we |     recording(status)
84|omni_we |   File "/data/app/ai/mini-omni/webui/omni_streamlit.py", line 158, in recording
84|omni_we |     stream = audio.open(
84|omni_we |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pyaudio/__init__.py", line 639, in open
84|omni_we |     stream = PyAudio.Stream(self, *args, **kwargs)
84|omni_we |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pyaudio/__init__.py", line 441, in __init__
84|omni_we |     self._stream = pa.open(**arguments)
84|omni_we | OSError: [Errno -9996] Invalid input device (no default output device)

**Comment by Emotibot5** [comment]
<img width="856" alt="image" src="https://github.com/user-attachments/assets/38aa441b-d84f-41dd-9194-8e864acbb2ff">

**Comment by mini-omni** [comment]
Did you start streamlit remotely or in your local computer? You need to start the streamlit locally with Pyaduio installed. Please refer: https://github.com/gpt-omni/mini-omni?tab=readme-ov-file#faq

**Comment by scalar27** [comment]
I get a similar error usually (local streamlit) but typically it works the second time I hit start.

**Comment by mini-omni** [comment]
> I get a similar error usually (local streamlit) but typically it works the second time I hit start.

yes, it shows a overflow error (I don't know the reason, sad) and the second time it works fine.

I will close it for now, please feel free to re-open.
