### ISSUE TITLE
gradio web report error after recording #69

### ISSUE THREAD

**Issue by Emotibot5** [gpt-omni/mini-omni#70]
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
85|omni_gradio_web  |     lambda source, handler: handler(source)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
85|omni_gradio_web  |     schema = self._handler(source_type)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
85|omni_gradio_web  |     schema = self._generate_schema_inner(obj)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
85|omni_gradio_web  |     return self.match_type(obj)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
85|omni_gradio_web  |     return self._match_generic_type(obj, origin)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
85|omni_gradio_web  |     return self._union_schema(obj)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
85|omni_gradio_web  |     choices.append(self.generate_schema(arg))
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
85|omni_gradio_web  |     schema = self._generate_schema_inner(obj)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
85|omni_gradio_web  |     return self.match_type(obj)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
85|omni_gradio_web  |     return self._unknown_type_schema(obj)
85|omni_gradio_web  |   File "/home/ops/anaconda3/envs/omni/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
85|omni_gradio_web  |     raise PydanticSchemaGenerationError(
85|omni_gradio_web  | pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
85|omni_gradio_web  | If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
85|omni_gradio_web  | For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

**Comment by mini-omni** [comment]
which gradio version did you use?

**Comment by Emotibot5** [comment]
gradio          version:        4.42.0

**Comment by mini-omni** [comment]
please try following versions
```
pydantic                  2.8.2
pydantic_core             2.20.1
```

**Comment by mincomp** [comment]
downgrade to `fastapi==0.112.4` as mentioned in https://github.com/jhj0517/Whisper-WebUI/issues/258 fixed it

**Comment by mini-omni** [comment]
I will close it for now, please feel free to re-open.
