### ISSUE TITLE
What are the advantages of audio-to-audio compared to text-to-audio?

### ISSUE THREAD

**Issue by beetlebum233** [gpt-omni/mini-omni#72]
Mini-Omni提供了一个很棒的思路，可以将LLM结合TTS，与等待LLM流式返回后再传给TTS做合成相比，无疑在降低延时方面理论上有显著提升。

但对于输入的部分，跟调用ASR后得到文本，再将文本作为模型输入相比，将语音编码后直接输入到模型有什么效果上或者延时上的优势吗？

提出这样的问题主要是因为，我们在人机对话的过程中，如果要降低响应延时，怎么在vad方面做优化是一个很大的难点，如果按照传统的vad时长800ms作为完成说话的标志，那么先调用asr再将文本输入到模型，并不会比语音直接输入到模型慢；而如果像`[omni_streamlit.py](https://github.com/gpt-omni/mini-omni/blob/main/webui/omni_streamlit.py)`一样将vad设置成100ms确实会比asr更快，但是在实践上会很容易导致误打断。

本人的理解是，从输入这里的优化方向，是怎么让vad跟推理并行，才能最有效地降低前半部分的耗时。

如果有哪些方面说得不对，还请指教，谢谢！

---
Translated By GPT-4o:

Mini-Omni provides a great idea by combining LLM with TTS. Compared to waiting for LLM to return results in a streaming manner and then passing them to TTS for synthesis, it undoubtedly has a significant theoretical improvement in reducing latency.

However, for the input part, compared to obtaining text after calling ASR and then using the text as model input, what are the advantages in terms of effect or latency of directly encoding the speech and inputting it into the model?

The main reason for raising this question is that, in the process of human-computer interaction, if we want to reduce response latency, optimizing VAD is a major challenge. If we follow the traditional VAD duration of 800ms as a marker for completing speech, then calling ASR first and then inputting the text into the model would not be slower than directly inputting the speech into the model. However, if we set VAD to 100ms as in `[omni_streamlit.py](https://github.com/gpt-omni/mini-omni/blob/main/webui/omni_streamlit.py)`, it would indeed be faster than ASR, but in practice, it can easily lead to false interruptions.

My understanding is that the optimization direction for the input part is how to make VAD and inference parallel to most effectively reduce the time consumption of the first half.

If there are any aspects that are incorrect, please advise. Thank you!

**Comment by mini-omni** [comment]
1. 直接将音频信息输入给大模型，在有对应数据的情况下，模型可以理解说话人的情绪及其它非语义信息。而这些信息是纯文本中不包含的。
2. 这里语音输入也可以模仿流式asr，可以流式提取音频特征，可以加快处理速度

---

1. Directly inputting audio information into the large model allows it to understand the speaker's emotions and other non-semantic information, provided that corresponding data is available. These are pieces of information that are not present in pure text.
2. The speech input here can also mimic streaming ASR, enabling the streaming extraction of audio features, which can speed up the processing.

**Comment by beetlebum233** [comment]
针对 2. 这一点，是不是意味着此时 Mini-Omni 除了LLM，还内置了一个提取音频特征的模型？还是说 Mini-Omni 的语言模型自己能判断用户什么时候结束了说话，什么时候开始推理？
---
Regarding 2. , does this mean that at this point Mini-Omni not only includes an LLM but also has a built-in model for extracting audio features? Or does it mean that the language model of Mini-Omni can itself determine when the user has finished speaking and when to start reasoning?

**Comment by mini-omni** [comment]
这里音频特征提取用的预训练好的whisper encoder，判断用户什么时候结束说话是外置的VAD来实现的

The audio feature extraction here uses a pre-trained Whisper encoder, and determining when the user finishes speaking is achieved through an external VAD (Voice Activity Detection).

**Comment by szad670401** [comment]
是否可能改成全双工的模式(Full-Duplex)?
输入audio的同时输出audio  ,input audio  stream和 output audio stream 可以实时做blending这样子. 这样latency有可能可以更低？ 例如人类多数情况下可以在未完全说完话的情况下抢答。类似于moshi , https://github.com/kyutai-labs/moshi

**Comment by mini-omni** [comment]
> 是否可能改成全双工的模式(Full-Duplex)?

是可以的，只是对数据要求会更高一些，以及对模型的鲁棒性要求也更高。

**Comment by aidenyzhang** [comment]
> 1. 直接将音频信息输入给大模型，在有对应数据的情况下，模型可以理解说话人的情绪及其它非语义信息。而这些信息是纯文本中不包含的。
> 2. 这里语音输入也可以模仿流式asr，可以流式提取音频特征，可以加快处理速度
> 
> 1. Directly inputting audio information into the large model allows it to understand the speaker's emotions and other non-semantic information, provided that corresponding data is available. These are pieces of information that are not present in pure text.
> 2. The speech input here can also mimic streaming ASR, enabling the streaming extraction of audio features, which can speed up the processing.

对于这里的第一点有些疑问：
whisper本身是个ASR模型，他的encoder特征富含充足的语义信息，但是未必还保留了“人的情绪”这种非语义信息。直接输入音频或许会保留更多的非语义信息？
请问这里作者是怎么看待这个问题的呢？

**Comment by mini-omni** [comment]
@aidenyzhang 这里只是我们选用whisper对音频进行编码，因为它已经可以理解音频中的语义，训练上更简单，也可以选择其它的编码方式，比如也可以用SNAC类似的audio codec方案。
