### ISSUE TITLE
Chinese asr task support 

### ISSUE THREAD

**Issue by hosea7456** [gpt-omni/mini-omni#74]
Does the mini-omni framework support Chinese speech-to-text? According to my experience, chinese audio file cannot be recognized when I running the 'inference.py'.
I'm eagerly awaiting your response. Thanks in advance!

**Comment by mini-omni** [comment]
As we use the whisper encoder, and during my test, I find that it can undertand basic chinese questions, but the output is only english. Please refer: https://github.com/gpt-omni/mini-omni?tab=readme-ov-file#faq

**Comment by mini-omni** [comment]
I will close it for now, please feel free to re-open.
