### ISSUE TITLE
Are there any plans to open up other TTS? 

### ISSUE THREAD

**Issue by MathewWuZJ** [gpt-omni/mini-omni#77]
I haven't run the project yet, looking at the description and now specifying a unique timbre, the business hopes to expand the emptiness, and hopes to support capabilities such as timbre cloning and timbre transposition, and is there any plan to support other SOTA TTS or open related capabilities in the future? For example, working with chatTTS

还没run项目，看描述现在指定了唯一的音色，业务希望扩展可用性，希望支持音色克隆、音色变调等能力，后期是否有计划支持其他SOTA TTS 或开放相关能力？比如与chatTTS合作 

BTW 中秋快乐：）

**Comment by mini-omni** [comment]
hi, 由于数据限制，目前没有计划支持其它音色。


Hi, due to data limitations, there are currently no plans to support other voice tones.

**Comment by MathewWuZJ** [comment]
明白，另外，我在 Zhifei 的推上留言了联系方式，希望和你交流，如果条件允许，可以加我联系，非常感谢。

I left you my contact infos on X(@XieZhifei14110) and hope to communicate with you guys. If possible, adding my contacts is perfect. Thx.

**Comment by mini-omni** [comment]
> 明白，另外，我在 Zhifei 的推上留言了联系方式，希望和你交流，如果条件允许，可以加我联系，非常感谢。
> 
> I left you my contact infos on X(@XieZhifei14110) and hope to communicate with you guys. If possible, adding my contacts is perfect. Thx.

你可以在邮箱里留联系方式哈， 具体可以参考arxiv tech report.
