### ISSUE TITLE
 the total number of parameters in the model?

### ISSUE THREAD

**Issue by Joseph513shen** [gpt-omni/mini-omni#8]
1.how many parameters does mini-omni have？
2.Are there any pre-trained models available for download?

**Comment by superFilicos** [comment]
1. about 0.6B
2. on our huggingface link.

**Comment by Joseph513shen** [comment]
> 1. about 0.6B
> 2. on our huggingface link.
thank u. that's really tiny
1.and i find "[lit_model.pth](https://huggingface.co/gpt-omni/mini-omni/blob/main/lit_model.pth)" ,is that ?
2.The training code has not been uploaded yet, only the inference code has been uploaded?

**Comment by superFilicos** [comment]
yes!
