### ISSUE TITLE
关于loss函数

### ISSUE THREAD

**Issue by anliyuan** [gpt-omni/mini-omni#81]
大佬，我在尝试复现训练过程，想问下训练过程中loss是怎么计算的呢？

**Comment by mini-omni** [comment]
hi, loss计算与文本llm的loss计算相似的，都是通过做next token prediction的方式。建议参考：https://github.com/Lightning-AI/litgpt/blob/main/litgpt/pretrain.py#L312

**Comment by anliyuan** [comment]
非常感谢答复。明白了。
