### ISSUE TITLE
OSError: [Errno -9996] Invalid input device (no default output device)

### ISSUE THREAD

**Issue by tianke0711** [gpt-omni/mini-omni#89]
运行下面代码在服务器上：

pip install PyAudio==0.2.14
API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py

出现了了问题

OSError: [Errno -9996] Invalid input device (no default output device)

我看github上 
运行在locally
我无法理解本地在运行

API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py

**Comment by mini-omni** [comment]
@tianke0711 本地运行，是指在可以使用mic的机器上执行streamlit程序，启动前端。你在服务器启动streamlit，是无法获取本地机器的mic输入的。

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.

**Comment by ffhelly** [comment]
> @tianke0711 本地运行，是指在可以使用mic的机器上执行streamlit程序，启动前端。你在服务器启动streamlit，是无法获取本地机器的mic输入的。

那这个不能在服务端部署吗？ 只能本机去部署 然后执行整个流程的吗？
