### ISSUE TITLE
Hello , does dataset open?

### ISSUE THREAD

**Issue by MonolithFoundation** [gpt-omni/mini-omni#9]
Could you provide more training code? For instance, alignment pre-training and SFT configurations? Additionally, the dataset appears to be unavailable.

**Comment by superFilicos** [comment]
![dd7e8443b3bdd7655545e7332d4d4a1](https://github.com/user-attachments/assets/82dc38f1-fb9d-4dba-acc9-4c8dc270f3a5)
We are working on the dataset.

**Comment by kunci115** [comment]
is it possible if we finetune output voice accent?

**Comment by mini-omni** [comment]
> is it possible if we finetune output voice accent?

yes, but you need to prapare the data with new accent first and finetune with it.

**Comment by MonolithFoundation** [comment]
hello, looks like the dataset still not uploaded succesfully?

**Comment by mini-omni** [comment]
> hello, looks like the dataset still not uploaded succesfully?

hi, we will upload it to hf in 2-3 days.

**Comment by mini-omni** [comment]
dupe with: https://github.com/gpt-omni/mini-omni/issues/2, I'll close it for now, feel free to re-open.

**Comment by itaowei** [comment]
> > hello, looks like the dataset still not uploaded succesfully?
> 
> hi, we will upload it to hf in 2-3 days.

May I ask where can I access the dataset? I cannot find it in hf.

**Comment by mini-omni** [comment]
the dataset is uploaded, path: https://huggingface.co/datasets/gpt-omni/VoiceAssistant-400K

**Comment by MonolithFoundation** [comment]
Hello, @mini-omni  noticed that the data only contains in speech, no out speech.

**Comment by mini-omni** [comment]
> Hello, @mini-omni noticed that the data only contains in speech, no out speech.

we did not save the output speech audio file, but only keeped the snac tokens of the output audio. If you need to the output audio you can use snac model to decode it to wavs.

**Comment by MonolithFoundation** [comment]
@mini-omni Does the snac ids decode can 100% recover audio

**Comment by MonolithFoundation** [comment]
@mini-omni  hi, may I ask which sample rate of snac were used here?

**Comment by mini-omni** [comment]
@MonolithFoundation I don't think it will 100% recover, but pretty good. The sample rating 24kHz.

**Comment by MonolithFoundation** [comment]
@mini-omni Hi, if snac is so good, why some models still using flow matching or diffusion way to geneate audios? I listened the SNAC trained model, mostly lack of emotions and stops with signs etc., how do u think

**Comment by mini-omni** [comment]
@MonolithFoundation I think flow matching and diffusion work better for acoustic details.

**Comment by MonolithFoundation** [comment]
but flow matching hard to streaming.
