### ISSUE TITLE
API_URL=http://0.0.0.0:60808/chat python3 webui/omni_gradio.py

### ISSUE THREAD

**Issue by tianke0711** [gpt-omni/mini-omni#90]
运行下面命令在服务器上 
API_URL=http://0.0.0.0:60808/chat python3 webui/omni_gradio.py

没有显示成功了
API_URL=http://0.0.0.0:60808/chat python3 webui/omni_gradio.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

访问不成功

**Comment by yufeng97** [comment]
服务器是本机吗，如果是远程的加上`--port 7860`
```bash
API_URL=http://0.0.0.0:60808/chat python3 webui/omni_gradio.py--port 7860
``` 
应该能访问

**Comment by mini-omni** [comment]
如果是在服务器上启动gradio，可以试试share=True，主要保证你本地机器与服务器的访问是通畅的，比如你可以访问到服务器上的7860这个端口（这过程中可能涉及一些接口转发之类的问题）。也可以直接在gradio官方帮助做的demo上体验：https://huggingface.co/spaces/gradio/omni-mini

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
