### ISSUE TITLE
关于layershift的作用

### ISSUE THREAD

**Issue by anliyuan** [gpt-omni/mini-omni#93]
大佬，在读代码时候不太明白layershift的作用是什么，可以解答一下吗？

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.

**Comment by Dongjie-Cheng** [comment]
> 不同的audio head并行输出的时候，每个head需要享受它自己的输入序列。 可以理解为每一个audiohead 需要一个自己的小vocab。所以这些token的序号需要在原始snac的序号上 + （head_number * snac_vocab_size），这就是layershift，对于序号的layer状的shift。

大佬您好，有几个点感到非常困惑。
我的理解是参数方面模型只有一个head，参考forward的函数，每一层的token都来源于相同的logits，只是不同层限制argmax的范围。这样做为什么能做到七个audio层配合起来是良好的token组合，而且forward时甚至把八个序列直接取平均，这样不是就丢失了不同序列间的差异性？
不知道我的理解是否正确，还是我遗漏了论文的内容，期待回复！

**Comment by mini-omni** [comment]
@Dongjie-Cheng audio输出的不同层的logit不一样的，因为对应的head不一样。取平均只是我们做的初步实验，确实这里可能可以有更复杂的操作，比如可以用几层网络去fuse不同的文本或音频特征。
