### ISSUE TITLE
tts-adapter的作用

### ISSUE THREAD

**Issue by william-ljz** [gpt-omni/mini-omni#94]
您论文里面说会把codebook加入到tokenizer中，对于音频输出应该直接可以输入到解码器获得音频，我想问一下这里tts-adapter的作用是什么？

**Comment by superFilicos** [comment]
tts adapter可以训好之后让模型知道在这里做TTS的任务，让合成语音的任务尽可能少地干预大模型的权重

**Comment by mini-omni** [comment]
I'll close it for now, please feel free to re-open.
