### ISSUE TITLE
How to train this model with my own audio-to-audio data, any insturctions or documentations?

### ISSUE THREAD

**Issue by chaunceyliu30** [gpt-omni/mini-omni#95]
I'm not very familiar with llm training in multi-modality, like picture or audio, is there any instruction for starters or where can I find some tutorial material? Thanks.

**Comment by superFilicos** [comment]
Sorry, 这个建议您寻找一个大模型的训练框架然后改动model的建模方法，没有特别复杂，但是我们暂时还不会开源训练代码~

**Comment by mini-omni** [comment]
hi, @chaunceyliu30, you may refer to [litgpt](https://github.com/Lightning-AI/litgpt/blob/main/litgpt/pretrain.py) for the training scripts.
