### ISSUE TITLE
输入只能为单一模态吗，仅语音/文本，不能是语音+文本吗

### ISSUE THREAD

**Issue by chaunceyliu30** [gpt-omni/mini-omni#99]
想请教一下模型输入的时候看inference.py中只能输入单一模态，有没有办法既输入instruction（文本形式，指导模型如何回答）同时输入语音呢？

**Comment by superFilicos** [comment]
这个不可以的哈

**Comment by mini-omni** [comment]
@chaunceyliu30 由于目前训练主要是基于基础的问答数据，形式上暂时不支持text+audio的输入形式。
